export const photos = [
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0715.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0716.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0720.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0721.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0726.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0731.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0734.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0736.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0741.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0743.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0746.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0752.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0753.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0757.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0759.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0767.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0762.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0770.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0772.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0773.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0777.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0776.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0779.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0783.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0787.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0782.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0792.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0796.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0794.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0790.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0798.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0803.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0806.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0813.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0805.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0809.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0817.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0816.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0826.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0830.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0839.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0850.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0852.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0854.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0863.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0859.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0877.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0904.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0905.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0909.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0902.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0916.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0918.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0921.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0923.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0926.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0913.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0928.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0932.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0934.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0938.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0940.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0936.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0942.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0943.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0948.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0950.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0951.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0953.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0955.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0956.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0963.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0967.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0976.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0970.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0981.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0986.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0982.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0987.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0989.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0991.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0992.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0993.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0994.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0996.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1000.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0995.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1002.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_0998.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1003.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1005.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1006.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1008.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1013.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1014.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1015.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1019.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1026.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1024.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1020.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1028.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1029.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1031.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1030.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1034.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1032.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1036.webp",
    width: 4,
    height: 3,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1033.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
  {
    src: "https://data.diecezko.cz/2023/foto/IMG_1038.webp",
    width: 3,
    height: 4,
    alt: "Fotka z podzimního Diecézka 2023",
  },
];
